import './globals.css'
import type { Metadata } from 'next'
import { Lato } from 'next/font/google'

const lato = Lato({ 
  subsets: ['latin'], 
  weight: ['100', '300', '700', '900'] 
})

export const metadata: Metadata = {
  title: 'Netflix NG',
  description: 'Generated by create next app and supabase',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  )
}
